services:

  db-postgres:
    image: postgres:15-alpine
    container_name: zy_off_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: zy_off_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  cache-redis:
    image: redis:7-alpine
    container_name: zy_off_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: